# Generated by Django 5.0.6 on 2024-06-12 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocateStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=100)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cyber.computers')),
            ],
        ),
    ]
