# Generated by Django 5.0.6 on 2024-06-21 15:33

import datetime
import time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber', '0005_alter_allocateclass_class_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocateclass',
            name='class_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 18, 32, 59, 878359)),
        ),
        migrations.AlterField(
            model_name='allocatestudent',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 18, 32, 59, 878359)),
        ),
        migrations.AlterField(
            model_name='allocatevisitor',
            name='time_in',
            field=models.DateTimeField(default=time.time),
        ),
    ]
