# Generated by Django 5.0.6 on 2024-06-21 16:39

import datetime
import time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber', '0006_alter_allocateclass_class_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatevisitor',
            name='date_of_visit',
            field=models.DateField(default=datetime.date(2024, 6, 21)),
        ),
        migrations.AlterField(
            model_name='allocateclass',
            name='class_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 19, 39, 8, 191271)),
        ),
        migrations.AlterField(
            model_name='allocatestudent',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 19, 39, 8, 191271)),
        ),
        migrations.AlterField(
            model_name='allocatevisitor',
            name='time_in',
            field=models.TimeField(default=time.time),
        ),
        migrations.AlterField(
            model_name='allocatevisitor',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
