# Generated by Django 5.0.6 on 2024-06-22 10:00

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber', '0007_allocatevisitor_date_of_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocateclass',
            name='class_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 13, 0, 0, 331369)),
        ),
        migrations.AlterField(
            model_name='allocatestudent',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 13, 0, 0, 331369)),
        ),
        migrations.AlterField(
            model_name='allocatevisitor',
            name='date_of_visit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
