# Generated by Django 5.0.6 on 2024-06-22 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber', '0010_rename_allocatevisitor_allocatevisitors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocateclass',
            name='class_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 13, 10, 58, 456119)),
        ),
        migrations.AlterField(
            model_name='allocatestudent',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 13, 10, 58, 443099)),
        ),
    ]
