# Generated by Django 5.0.6 on 2024-06-22 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber', '0014_alter_allocateclass_class_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocateclass',
            name='class_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 18, 4, 46, 38771)),
        ),
        migrations.AlterField(
            model_name='allocatestudent',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 18, 4, 46, 38771)),
        ),
        migrations.AlterField(
            model_name='allocatevisitors',
            name='date_of_visit',
            field=models.DateField(default=datetime.date(2024, 6, 22)),
        ),
    ]
