# Generated by Django 5.0.6 on 2024-07-01 12:49

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber', '0018_alter_allocateclass_class_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocateclass',
            name='class_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 49, 43, 242859)),
        ),
        migrations.AlterField(
            model_name='allocatestudent',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 49, 43, 242859)),
        ),
        migrations.AlterField(
            model_name='allocatevisitors',
            name='date_of_visit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='allocatevisitors',
            name='time_in',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
