# Generated by Django 5.0.6 on 2024-08-06 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber', '0020_alter_allocateclass_class_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocateclass',
            name='class_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 19, 37, 12, 245769)),
        ),
        migrations.AlterField(
            model_name='allocatestudent',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 19, 37, 12, 245769)),
        ),
        migrations.AlterField(
            model_name='allocatevisitors',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='allocatevisitors',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2024, 8, 6, 19, 37, 12, 245769)),
        ),
    ]
